version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-bot
    env_file:
      - .env
    depends_on:
      - bot_db
    networks:
      - bot-network
    volumes:
      - .:/app
    restart: unless-stopped

  bot_db:
    image: postgres:13
    container_name: telegram-bot-db
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${DB_LOCAL_PORT}:5432"

    environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=${DB_NAME}
    networks:
      - bot-network
networks:
    bot-network:
      external: false
volumes:
  db-data:
